from colorama import Fore, init,Back, Style
init()

DEBUG = 'a'
# sizes
HEIGHT = 40
MAXWIDTH = 600
WIDTH = 120
PLACEWIDTH = 40
SKY = 3
GROUND = 3

# colors
RESET = Style.RESET_ALL
GREY = Fore.LIGHTBLACK_EX
CYAN = Fore.LIGHTCYAN_EX
RED = Fore.LIGHTRED_EX
BLUE = Fore.BLUE
GCOLOR = Fore.LIGHTBLUE_EX 
WHITE=Fore.WHITE
ICE=Fore.CYAN


# misc
COIN = Fore.LIGHTYELLOW_EX+'$'+Fore.RESET
STAR = Fore.LIGHTGREEN_EX+'p'+Fore.RESET
